---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ash.dev.ash.dev
  resources:
  - ashes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ash.dev.ash.dev
  resources:
  - ashes/finalizers
  verbs:
  - update
- apiGroups:
  - ash.dev.ash.dev
  resources:
  - ashes/status
  verbs:
  - get
  - patch
  - update
