apiVersion: ash.dev.ash.dev/v1
kind: Ash
metadata:
  name: test
  namespace: demo
spec:
  deploymentName:
  replicas: 3
  container:
    image: ashraf10039/httpapiserver
    port: 8081
  service:
    serviceName: "my-bro"
    serviceType: "ClusterIP"
    servicePort: 8081